#Start with a base image containing Java runtime
FROM openjdk:17-jdk-slim as build

#Information around who maintains the image
MAINTAINER klsites.com.br

# Add the application's jar to the container
COPY target/account.jar account.jar

#execute the application
ENTRYPOINT ["java","-jar","/account.jar"]